# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
#
# Playbook to register License on Local Manager(s) with NSX Appliance
#
- hosts: 127.0.0.1
  connection: local
  become: true
  vars_files:
    - answerfile.yml
  tasks:
    - name: Add NSX License to Local Manager
      vmware.ansible_for_nsxt.nsxt_licenses:
        hostname: "{{ nsx_lm_1.hostname }}"
        username: "{{ username }}"
        password: "{{ admin_password }}"
        validate_certs: "{{ validate_certs }}"
        license_key: "{{ license_key }}"
        state: "{{ state }}"
      with_items:
        - "{{ local_managers }}"
