---
#
# Playbook to make the Global Manager Active
#
- hosts: 127.0.0.1
  connection: local
  become: true
  vars_files:
    - answerfile.yml
  tasks:
    - name: Make the Global Manager Active
      vmware.ansible_for_nsxt.nsxt_global_manager_enable_service:
        hostname: "{{ nsx_gm_1.fqdn }}"
        username: "{{ username }}"
        password: "{{ nsx_gm_1.password }}"
        validate_certs: "{{ validate_certs }}"
        id: "{{ nsx_gm_1.id }}"
        display_name: "{{ nsx_gm_1.display_name }}"
