# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
#
# Playbook to register Compute Managers with NSX Appliance
#
- hosts: 127.0.0.1
  connection: local
  become: true
  vars_files:
    - answerfile.yml
  tasks:
    - name: Register Compute Manager (Management vCenter) on GM
      vmware.ansible_for_nsxt.nsxt_fabric_compute_managers:
        hostname: "{{ nsx_standby_gm_1.hostname }}"
        username: "{{ username }}"
        password: "{{ admin_password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{ compute_managers[2].vcenter_name }}"
        server: "{{ compute_managers[2].vcenter }}"
        origin_type: "{{ compute_managers[2].origin_type }}"
        credential:
          credential_type: "{{ compute_managers[2].credential_type }}"
          username: "{{ compute_managers[2].vcenter_user }}"
          password: "{{ compute_managers[2].vcenter_passwd }}"
        state: "{{ state }}"

    - name: Register Compute manager (Compute vCenter) on GM
      vmware.ansible_for_nsxt.nsxt_fabric_compute_managers:
        hostname: "{{ nsx_standby_gm_1.hostname }}"
        username: "{{ username }}"
        password: "{{ admin_password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{ compute_managers[3].vcenter_name }}"
        server: "{{ compute_managers[3].vcenter }}"
        origin_type: "{{ compute_managers[3].origin_type }}"
        credential:
          credential_type: "{{ compute_managers[3].credential_type }}"
          username: "{{ compute_managers[3].vcenter_user }}"
          password: "{{ compute_managers[3].vcenter_passwd }}"
        state: "{{ state }}"
